config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants, only: [:new, :show, :create, :index] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :name, :address, :city, :state, :zipcode, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating, :body, :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.order(updated_at: :desc).limit(10)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews.order(updated_at: :desc)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Your restaurant has been submitted.'
    else
      render 'new'
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)

    if @review.save
      redirect_to @restaurant, notice: 'Your review has been submitted.'
    else
      render 'new'
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h1>Good/Bad Ass Restaurants</h1>

<%= link_to 'Add A New Restaurant', new_restaurant_path %>
<br />

<uL>
<% @restaurants.each do |restaurant| %>
  <li><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add A New Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: 'Name of the restaurant: ', input_html: { maxlength: 20 } %>
  <%= f.input :address, label: 'Address: ', input_html: { maxlength: 20 } %>
  <%= f.input :city, label: 'City: ', input_html: { maxlength: 20 } %>
  <%= f.input :state, label: 'State: ', input_html: { maxlength: 20 } %>
  <%= f.input :zipcode, label: 'Zipcode: ', input_html: { maxlength: 20 } %>
  <%= f.input :description, as: 'text', label: 'What is the restaurant like? ' %>
  <%= f.input :category, collection: ['American', 'Chinese', 'Thai', 'Japanese', 'Italian', 'Everything'] %>
  <%= f.submit 'Submit' %>
<% end %>

<%= link_to '<= Back', :back %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.address %></h3>
<h3><%= @restaurant.city %></h3>
<h3><%= @restaurant.state %></h3>
<h3><%= @restaurant.zipcode %></h3>

<h2>Category:</h2>
<h4><%= @restaurant.category %></h3>
<h2>Description:</h2>
<p><%= @restaurant.description %></p>

<h2>Reviews:</h2>
<%= link_to 'Add A New Review', new_restaurant_review_path(@restaurant) %>
<ul>
<% @reviews.each do |review| %>
  <li><%= "#{review.rating} - #{review.body}" %></li>
<% end %>
</ul>
<br />
<%= link_to 'Home', root_path %>

app/views/reviews/new.html.erb
<h1>Add A New Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, collection: 1..5 %>
  <%= f.input :body, as: 'text', label: 'Your review of this restaurant: ' %>
  <%= f.submit 'Submit' %>
<% end %>

<%= link_to '<= Back', :back %>